version: '3.3'

services:
  content_db:
    container_name: content_db
    image: postgres:10-alpine
    restart: always
    env_file:
      - ./env/dev_env/content/postgres.env
    ports:
      - "5432:5432"

  user_db:
    container_name: user_db
    image: postgres:10-alpine
    restart: always
    env_file:
      - ./env/dev_env/user/postgres.env
    ports:
      - "5433:5432"

  user_interaction_db:
    container_name: user_interaction_db
    image: postgres:10-alpine
    restart: always
    env_file:
      - ./env/dev_env/user_interaction/postgres.env
    ports:
      - "5434:5432"

  lipi_redis:
    container_name: lipi_redis
    image: redis:4.0-alpine
    restart: always
    ports:
      - "6379:6379"

  base_image:
    build:
      context: .
    image: pratilipi_base_image

  content:
    build:
      context: ./content
      dockerfile: ./Dockerfile
    container_name: lipi_content
    image: lipi_content
    entrypoint: supervisord
    restart: always
    env_file:
      - ./env/dev_env/content/content.env
      - ./env/dev_env/content/postgres.env
      - ./env/dev_env/services.env
    depends_on:
      - content_db
      - lipi_redis
      - base_image
    network_mode: host

  user:
    build:
      context: ./user
      dockerfile: ./Dockerfile
    container_name: lipi_user
    image: lipi_user
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    restart: always
    env_file:
      - ./env/dev_env/user/user.env
      - ./env/dev_env/user/postgres.env
      - ./env/dev_env/services.env
    depends_on:
      - user_db
      - base_image
    network_mode: host

  user-interaction:
    build:
      context: ./user_interaction/
      dockerfile: ./Dockerfile
    container_name: lipi_user_interaction
    image: lipi_user_interaction
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:5000"
    restart: always
    env_file:
      - ./env/dev_env/user_interaction/user_interaction.env
      - ./env/dev_env/user_interaction/postgres.env
      - ./env/dev_env/services.env
    depends_on:
      - user_interaction_db
      - base_image
    network_mode: host
