version: '3.3'

services:
  content_db:
    container_name: content_db
    image: postgres:10-alpine
    restart: always
    env_file:
      - postgres.env
    ports:
      - "7001:5432"

  user_db:
    container_name: user_db
    image: postgres:10-alpine
    restart: always
    env_file:
      - postgres.env
    ports:
      - "7002:5432"
  
  user_interaction_db:
    container_name: user_interaction_db
    image: postgres:10-alpine
    restart: always
    env_file:
      - postgres.env
    ports:
      - "7003:5432"

  lipi_redis:
    container_name: lipi_redis
    image: redis:4.0-alpine
    restart: always

  user:
    build: user
    container_name: lipi_user
    image: lipi_user
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    env_file:
      - user.env
    ports:
      - "8000:8000"
    depends_on:
      - user_db

  content:
    build: content
    container_name: lipi_content
    image: lipi_content
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    env_file:
      - content.env
    ports:
      - "3000:8000"
    depends_on:
      - content_db
      - lipi_redis

  user_interaction:
    build: user_interaction
    container_name: lipi_user_interaction
    image: lipi_user_interaction
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    env_file:
      - user_interaction.env
    ports:
      - "5000:8000"
    depends_on:
      - user_interaction_db